name: Workflow example # Name of the workflow
on: push # Events that trigger the jobs

jobs: # List of tasks
  say-hi: # id of the job
    name: Say hi # Name of the job
    runs-on: ubuntu-latest # SO of the server
    steps: # List of subtasks
      - name: Separator # Name of the subtask
        run: echo "#######" # Command to execute

      - name: Say good morning # Name of the subtask
        run: echo "Good morning Vietnam" # Command to execute

  say-bye:
    name: Say say-bye
    runs-on: ubuntu-latest
    steps:
      - uses: lgmorand/github-action-hello@v2
        with:
          firstname: gerard
          firstname2: baste

      - name: Say good night
        run: echo "Good night Vietnam"
